version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types: ['minor', 'patch']
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: npm
    directory: /infra
    schedule:
      interval: weekly
    groups:
      cdk:
        patterns: ['*']
    commit-message:
      prefix: 'chore(deps)'
