/**
 * The front-line layer (sand-g80.1): where the Western Front ran, snapshot by
 * dated snapshot, from the end of the war of movement to the Armistice.
 *
 * The data is `content/shared/geo/front/western-front.geojson`, generated by
 * `npm run front` and served from the assets bucket like the borders. The whole
 * series is one small file (about 11 kB gzip), so it is fetched once and the
 * clock picks a snapshot out of it — `snapshotAt` — rather than the map
 * re-fetching every time the reader scrubs.
 *
 * The line is drawn three times: a wash on the German side, a wash on the
 * Allied side, and the line itself between them. The washes are the same
 * geometry with `line-offset`, which offsets relative to the direction the
 * coordinates run in — and every snapshot runs north to south, which
 * `scripts/build-front.ts` checks, so a positive offset is reliably west and a
 * negative one east. A snapshot the sources only fix loosely is drawn dashed.
 */
import type { LineLayerSpecification } from 'maplibre-gl';
import type { MapTheme } from './style.js';

export const FRONT_SOURCE = 'front';
export const FRONT_BASE_URL = '/assets/geo/front';

/** `pack.frontLine` names the series; today the only one is `western-front`. */
export const frontUrl = (series: string, base = FRONT_BASE_URL) => `${base}/${series}.geojson`;

export type FrontPrecision = 'high' | 'medium' | 'low';

export interface FrontCitation {
  source: string;
  pages?: string;
  note?: string;
}

export interface FrontFeature {
  type: 'Feature';
  id?: string;
  properties: {
    date: string;
    /** Epoch ms of the snapshot's day, precomputed by the generator. */
    at: number;
    label: string;
    precision: FrontPrecision;
    summary: string;
    sources: FrontCitation[];
    through: string[];
    lengthKm: number;
  };
  geometry: { type: 'LineString'; coordinates: [number, number][] };
}

export interface FrontGeoJSON {
  type: 'FeatureCollection';
  attribution?: string;
  /** How the geometry was arrived at, and how good it is. */
  method?: string;
  features: FrontFeature[];
}

export async function fetchFront(series: string, base = FRONT_BASE_URL): Promise<FrontGeoJSON> {
  const res = await fetch(frontUrl(series, base));
  if (!res.ok) throw new Error(`front line ${series}: HTTP ${res.status}`);
  return (await res.json()) as FrontGeoJSON;
}

/**
 * The snapshot in force at `at`: the most recent one dated at or before it.
 * Undefined before the first, because there was no continuous front to draw —
 * the line only becomes a fact on 25 November 1914, and drawing the earliest
 * snapshot through the march to the Marne would be a lie about the campaign
 * the reader is watching.
 */
export function snapshotAt(geo: FrontGeoJSON, at: number): FrontFeature | undefined {
  let found: FrontFeature | undefined;
  for (const f of geo.features) {
    if (f.properties.at > at) break;
    found = f;
  }
  return found;
}

/** One snapshot on its own, which is all the map source ever holds. */
export function only(feature: FrontFeature | undefined): FrontGeoJSON {
  return { type: 'FeatureCollection', features: feature ? [feature] : [] };
}

/** Width of the no-man's-land wash on each side, in pixels, by zoom. */
const WASH_WIDTH: LineLayerSpecification['paint'] = {
  'line-width': ['interpolate', ['linear'], ['zoom'], 4, 5, 7, 11, 10, 26],
};

export function frontLayers(theme: MapTheme): LineLayerSpecification[] {
  const dark = theme === 'dark';
  // --army-1 and --french: the alliance colours the rest of the map already uses.
  const central = dark ? '#d45b3f' : '#9a2e22';
  const entente = dark ? '#6fa6c4' : '#24566e';
  const line = dark ? '#e9e1cb' : '#241f16';
  const halo = dark ? '#10161a' : '#e6dfcb';

  const wash = (id: string, color: string, offset: number): LineLayerSpecification => ({
    id,
    type: 'line',
    source: FRONT_SOURCE,
    layout: { 'line-join': 'round', 'line-cap': 'round' },
    paint: {
      'line-color': color,
      'line-opacity': dark ? 0.34 : 0.28,
      'line-blur': 3,
      'line-offset': [
        'interpolate',
        ['linear'],
        ['zoom'],
        4,
        offset * 3,
        7,
        offset * 6,
        10,
        offset * 14,
      ],
      ...WASH_WIDTH,
    },
  });

  const body = (id: string, dashed: boolean): LineLayerSpecification => ({
    id,
    type: 'line',
    source: FRONT_SOURCE,
    filter: dashed ? ['==', ['get', 'precision'], 'low'] : ['!=', ['get', 'precision'], 'low'],
    layout: { 'line-join': 'round', 'line-cap': 'round' },
    paint: {
      'line-color': line,
      'line-width': ['interpolate', ['linear'], ['zoom'], 4, 1.1, 7, 2, 10, 3.2],
      'line-opacity': 0.92,
      ...(dashed ? { 'line-dasharray': [3, 2] as [number, number] } : {}),
    },
  });

  return [
    // A quiet halo so the line stays legible over the borders fill.
    {
      id: 'front-halo',
      type: 'line',
      source: FRONT_SOURCE,
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': halo,
        'line-opacity': 0.55,
        'line-width': ['interpolate', ['linear'], ['zoom'], 4, 3, 7, 5, 10, 7],
      },
    },
    // North to south, so a negative offset is the eastern — German-held — side.
    wash('front-wash-central', central, -1),
    wash('front-wash-entente', entente, 1),
    body('front-line', false),
    body('front-line-approx', true),
  ];
}

/** Every layer id this module mounts, for teardown on a theme change. */
export const FRONT_LAYER_IDS = [
  'front-halo',
  'front-wash-central',
  'front-wash-entente',
  'front-line',
  'front-line-approx',
] as const;
